#include "usart.h"
#include <stdio.h>

/* Private variables */
static uint8_t rx_buffer[USART0_RX_BUFFER_SIZE];
static uint8_t tx_buffer[USART0_TX_BUFFER_SIZE];
static volatile uint16_t rx_head = 0;
static volatile uint16_t rx_tail = 0;
static volatile uint16_t tx_head = 0;
static volatile uint16_t tx_tail = 0;
static volatile uint8_t tx_busy = 0;
static volatile uint8_t loopback_enabled = 0;
static usart_rx_callback_t rx_callback = NULL;

/* Private function prototypes */
static uint8_t USART0_BufferIsFull(uint16_t head, uint16_t tail, uint16_t size);
static uint8_t USART0_BufferIsEmpty(uint16_t head, uint16_t tail);
static void USART0_EnableInterrupts(void);
static void USART0_DisableInterrupts(void);

/*!
    \brief      Initialize USART0 on PA9/PA10 for communication
    \param[in]  none
    \param[out] none
    \retval     none
*/
void USART0_Init(void)
{
    /* Enable GPIO and USART clocks */
    rcu_periph_clock_enable(USART0_GPIO_RCU);
    rcu_periph_clock_enable(USART0_RCU);
    
    /* Configure PA9 as TX and PA10 as RX on the default USART0 mapping. */
    gpio_init(USART0_GPIO, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, USART0_TX_PIN);
    gpio_init(USART0_GPIO, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, USART0_RX_PIN);
    
    /* USART parameter configuration */
    usart_deinit(USART0_PERIPH);
    usart_baudrate_set(USART0_PERIPH, USART0_BAUDRATE);
    usart_word_length_set(USART0_PERIPH, USART0_WORD_LENGTH);
    usart_stop_bit_set(USART0_PERIPH, USART0_STOP_BITS);
    usart_parity_config(USART0_PERIPH, USART0_PARITY);
    usart_hardware_flow_rts_config(USART0_PERIPH, USART0_HARDWARE_FLOW);
    usart_hardware_flow_cts_config(USART0_PERIPH, USART_CTS_DISABLE);

    usart_receive_config(USART0_PERIPH, USART_RECEIVE_ENABLE);
    usart_transmit_config(USART0_PERIPH, USART_TRANSMIT_ENABLE);
    
    
    /* Enable USART */
    usart_enable(USART0_PERIPH);
    
    /* Clear buffers */
    USART0_ClearBuffers();
    
    /* Enable USART receive interrupt */
    usart_interrupt_enable(USART0_PERIPH, USART_INT_RBNE);
    
    /* Configure NVIC for USART0. */
    NVIC_CONFIG(USART0_IRQN, USART0_PRIORITY_GROUP, USART0_PRIORITY_SUBGROUP);
    
    /* Debug output must not be mixed with automatic receive echo. */
    USART0_LoopbackDisable();
}

/*!
    \brief      Enable loopback mode (echo received data)
    \param[in]  none
    \param[out] none
    \retval     none
*/
void USART0_LoopbackEnable(void)
{
    loopback_enabled = 1;
}

/*!
    \brief      Disable loopback mode
    \param[in]  none
    \param[out] none
    \retval     none
*/
void USART0_LoopbackDisable(void)
{
    loopback_enabled = 0;
}

/*!
    \brief      Send a byte via USART0
    \param[in]  data: byte to send
    \param[out] none
    \retval     status of operation
*/
usart_status_t USART0_SendByte(uint8_t data)
{
    USART0_DisableInterrupts();
    
    /* Check if TX buffer is full */
    if (USART0_BufferIsFull(tx_head, tx_tail, USART0_TX_BUFFER_SIZE)) {
        USART0_EnableInterrupts();
        return USART_STATUS_BUFFER_FULL;
    }
    
    /* Add data to TX buffer */
    tx_buffer[tx_head] = data;
    tx_head = (tx_head + 1) % USART0_TX_BUFFER_SIZE;
    
    /* If transmitter is idle, start transmission */
    if (!tx_busy) {
        tx_busy = 1;
        usart_interrupt_enable(USART0_PERIPH, USART_INT_TBE);
    }
    
    USART0_EnableInterrupts();
    return USART_STATUS_OK;
}

/*!
    \brief      Send a string via USART0
    \param[in]  str: null-terminated string to send
    \param[out] none
    \retval     status of operation
*/
usart_status_t USART0_SendString(const char *str)
{
    usart_status_t status;
    
    while (*str) {
        status = USART0_SendByte(*str++);
        if (status != USART_STATUS_OK) {
            return status;
        }
    }
    
    return USART_STATUS_OK;
}

/*!
    \brief      Retarget the C library standard output to USART0
    \param[in]  ch: character generated by printf
    \param[in]  stream: standard library stream, unused by the UART driver
    \retval     transmitted character on success, EOF on failure
    \note       Call printf only from thread/main-loop context.
*/
int fputc(int ch, FILE *stream)
{
    usart_status_t status;

    (void)stream;
    do {
        status = USART0_SendByte((uint8_t)ch);
    } while (status == USART_STATUS_BUFFER_FULL);

    if (status != USART_STATUS_OK) {
        return EOF;
    }
    return ch;
}

/*!
    \brief      Receive a byte from USART0 buffer
    \param[in]  none
    \param[out] none
    \retval     received byte (0 if buffer empty)
*/
uint8_t USART0_ReceiveByte(void)
{
    uint8_t data = 0;
    
    USART0_DisableInterrupts();
    
    if (!USART0_BufferIsEmpty(rx_head, rx_tail)) {
        data = rx_buffer[rx_tail];
        rx_tail = (rx_tail + 1) % USART0_RX_BUFFER_SIZE;
    }
    
    USART0_EnableInterrupts();
    
    return data;
}

/*!
    \brief      Check if data is available in RX buffer
    \param[in]  none
    \param[out] none
    \retval     1 if data available, 0 otherwise
*/
uint8_t USART0_IsDataAvailable(void)
{
    return !USART0_BufferIsEmpty(rx_head, rx_tail);
}

/*!
    \brief      Clear USART0 buffers
    \param[in]  none
    \param[out] none
    \retval     none
*/
void USART0_ClearBuffers(void)
{
    USART0_DisableInterrupts();
    
    rx_head = 0;
    rx_tail = 0;
    tx_head = 0;
    tx_tail = 0;
    tx_busy = 0;
    
    memset(rx_buffer, 0, sizeof(rx_buffer));
    memset(tx_buffer, 0, sizeof(tx_buffer));
    
    USART0_EnableInterrupts();
}

/*!
    \brief      Set RX callback function
    \param[in]  callback: function pointer to call when data received
    \param[out] none
    \retval     none
*/
void USART0_SetRxCallback(usart_rx_callback_t callback)
{
    rx_callback = callback;
}

/*!
    \brief      USART0 interrupt handler implementation
    \param[in]  none
    \param[out] none
    \retval     none
*/
static void USART0_HandlerInternal(void)
{
    /* Receive buffer not empty interrupt */
    if (usart_interrupt_flag_get(USART0_PERIPH, USART_INT_FLAG_RBNE) != RESET) {
        uint8_t data = usart_data_receive(USART0_PERIPH);
        
        /* Add to RX buffer */
        if (!USART0_BufferIsFull(rx_head, rx_tail, USART0_RX_BUFFER_SIZE)) {
            rx_buffer[rx_head] = data;
            rx_head = (rx_head + 1) % USART0_RX_BUFFER_SIZE;
            
            /* Call callback if set */
            if (rx_callback != NULL) {
                rx_callback(data);
            }
            
            /* Loopback: echo received data */
            if (loopback_enabled) {
                USART0_SendByte(data);
            }
        }
        
        usart_interrupt_flag_clear(USART0_PERIPH, USART_INT_FLAG_RBNE);
    }
    
    /* Transmit buffer empty interrupt */
    if (usart_interrupt_flag_get(USART0_PERIPH, USART_INT_FLAG_TBE) != RESET) {
        if (!USART0_BufferIsEmpty(tx_head, tx_tail)) {
            /* Send next byte */
            usart_data_transmit(USART0_PERIPH, tx_buffer[tx_tail]);
            tx_tail = (tx_tail + 1) % USART0_TX_BUFFER_SIZE;
        } else {
            /* No more data to send, disable TBE interrupt */
            usart_interrupt_disable(USART0_PERIPH, USART_INT_TBE);
            tx_busy = 0;
        }
        
        usart_interrupt_flag_clear(USART0_PERIPH, USART_INT_FLAG_TBE);
    }
}

/*!
    \brief      USART0 interrupt handler (to be called from gd32f30x_it.c)
    \param[in]  none
    \param[out] none
    \retval     none
*/
void USART0_IRQHandler_Internal(void)
{
    USART0_HandlerInternal();
}

/*!
    \brief      Check if buffer is full
    \param[in]  head: buffer head index
    \param[in]  tail: buffer tail index
    \param[in]  size: buffer size
    \param[out] none
    \retval     1 if full, 0 otherwise
*/
static uint8_t USART0_BufferIsFull(uint16_t head, uint16_t tail, uint16_t size)
{
    return ((head + 1) % size) == tail;
}

/*!
    \brief      Check if buffer is empty
    \param[in]  head: buffer head index
    \param[in]  tail: buffer tail index
    \param[out] none
    \retval     1 if empty, 0 otherwise
*/
static uint8_t USART0_BufferIsEmpty(uint16_t head, uint16_t tail)
{
    return head == tail;
}

/*!
    \brief      Disable USART0 interrupts (for critical sections)
    \param[in]  none
    \param[out] none
    \retval     none
*/
static void USART0_DisableInterrupts(void)
{
    usart_interrupt_disable(USART0_PERIPH, USART_INT_RBNE);
    usart_interrupt_disable(USART0_PERIPH, USART_INT_TBE);
}

/*!
    \brief      Enable USART0 interrupts
    \param[in]  none
    \param[out] none
    \retval     none
*/
static void USART0_EnableInterrupts(void)
{
    usart_interrupt_enable(USART0_PERIPH, USART_INT_RBNE);
    if (tx_busy) {
        usart_interrupt_enable(USART0_PERIPH, USART_INT_TBE);
    }
}
